/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vistas;

import Modelo.Analisis.Horizontal.Diferencias;
import Modelo.Analisis.Vertical.PorcientosIntegrados;
import Modelo.SituacionFinanciera;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.Map;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Diego EG
 */
public class AnalisisSF extends javax.swing.JFrame {

    SituacionFinanciera  sfX;
    SituacionFinanciera  sfY;
    
    public AnalisisSF(SituacionFinanciera acutual, SituacionFinanciera anterior) {
        initComponents();
        
        this.sfX = acutual; 
        this.sfY = anterior;
        
        this.sfX.leerEstadoFinanciero();
        this.sfY.leerEstadoFinanciero();
        
        cargarDatosTablaCuentas();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Fondo = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtCuentas = new javax.swing.JTable();
        btRegresar = new javax.swing.JButton();

        Fondo.setBackground(new java.awt.Color(153, 204, 255));

        jtCuentas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Cuenta", "Periodo Actual", "Periodo Anterior", "Porcentaje", "Diferencia"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jtCuentas);

        btRegresar.setBackground(new java.awt.Color(255, 255, 255));
        btRegresar.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        btRegresar.setText("Regresar");
        btRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btRegresarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout FondoLayout = new javax.swing.GroupLayout(Fondo);
        Fondo.setLayout(FondoLayout);
        FondoLayout.setHorizontalGroup(
            FondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(FondoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(FondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, FondoLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btRegresar))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 599, Short.MAX_VALUE))
                .addContainerGap())
        );
        FondoLayout.setVerticalGroup(
            FondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, FondoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btRegresar)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Fondo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Fondo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btRegresarActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_btRegresarActionPerformed

    
    public void cargarDatosTablaCuentas()
    {
        //Cuando se llama este metodo los 4 objetos de analisi deben estar creados
        DefaultTableModel modelo = (DefaultTableModel) this.jtCuentas.getModel();
        System.out.println("Vamos a llenar la tabla  de cuentas ");
        
        //Limpiando la tabla 
        try {
        int filas=this.jtCuentas.getRowCount();
            for (int i = 0;filas>i; i++) {
                modelo.removeRow(0);
            }
           
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Error al limpiar la tabla.");
        }
        
        
        String fila[] = new String[5];
        ArrayList<String> cuentasordenadasSF = sfX.obtenerNombresdeCuentasOrdenadas();
   
        Map<String,ArrayList<String>> cuentassfX = sfX.importarNombreySaldo();
        
        Map<String,ArrayList<String>> cuentassfY = sfY.importarNombreySaldo();
        
        
        
        PorcientosIntegrados porcientosIntegradosSFX = new PorcientosIntegrados(cuentassfX);
        
        //sfY.mostrarCuentas();
        Diferencias diferencias = new Diferencias(cuentassfY, cuentassfX);
        
        ArrayList<String> auxiliarparaDiferencias = diferencias.obtenerNombresCuentas();
        
        Map<String,String> analisisporcientosSFX = porcientosIntegradosSFX.AnalisisPorcientosIntegrados();
                
        Map<String, String> analisisDifernencias = diferencias.analisisDiferencias(auxiliarparaDiferencias);
        
        for (int i = 0; i < cuentasordenadasSF.size(); i++) {
            fila[0] = cuentasordenadasSF.get(i);
            //System.out.println("---> "+cuentasordenadasSF.get(i));
            
            fila[1] = obtenerSaldoCuentaenMap(cuentassfX, cuentasordenadasSF.get(i));
            fila[2] = obtenerSaldoCuentaenMap(cuentassfY, cuentasordenadasSF.get(i));
            fila[3] = analisisporcientosSFX.get(cuentasordenadasSF.get(i));
            fila[4] = analisisDifernencias.get(cuentasordenadasSF.get(i));
            fila[4] = analisisDifernencias.get(cuentasordenadasSF.get(i));
            
            modelo.addRow(fila);
            this.jtCuentas.setModel(modelo);
        }
        
    }
    
    public String obtenerSaldoCuentaenMap(Map<String, ArrayList<String>> cuentas, String cuentabuscada)
    {
        String saldo =  "";
        
        Iterator it = cuentas.keySet().iterator();
        
        while(it.hasNext())
        {
            String nombre = it.next().toString();
            //System.out.println("Nombre -->> "+nombre);
            ArrayList<String> datos = cuentas.get(nombre);
            if(cuentabuscada.contains(nombre))
            {
                if(datos.size()>0){
                    //System.out.println("Tam del arrlst "+datos.size());
                    //System.out.println("Encontre la cuenta "+ datos.get(0));
                    saldo = datos.get(0);
                }
            }
        }
                
        return saldo;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Fondo;
    private javax.swing.JButton btRegresar;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jtCuentas;
    // End of variables declaration//GEN-END:variables
}
