/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vistas;

/**
 *
 * @author super
 */
public class Cargar_Estado_Financiero extends javax.swing.JFrame {

    /**
     * Creates new form Cargar_Estado_Financiero
     */
    public Cargar_Estado_Financiero() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lb_titulo = new javax.swing.JLabel();
        lb_Instrucciones1 = new javax.swing.JLabel();
        lb_Instrucciones2 = new javax.swing.JLabel();
        lb_Instrucciones3 = new javax.swing.JLabel();
        lb_Instrucciones4 = new javax.swing.JLabel();
        lb_edos_cargados = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        Tabla_Estados_cargados = new javax.swing.JTable();
        btAbrirEstado = new javax.swing.JButton();
        btAnalizarEstado = new javax.swing.JButton();
        btRegresar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Cargar Estado Financiero");

        lb_titulo.setFont(new java.awt.Font("Rockwell", 0, 18)); // NOI18N
        lb_titulo.setText("INSTRUCCIONES");

        lb_Instrucciones1.setFont(new java.awt.Font("Rockwell", 0, 14)); // NOI18N
        lb_Instrucciones1.setText("Presiona el boton de \"Abrir Estado Financiero\" para cargar la información de un Estado Financiero.");

        lb_Instrucciones2.setFont(new java.awt.Font("Rockwell", 0, 14)); // NOI18N
        lb_Instrucciones2.setText("Este archivo debe de tener la extensión:       *.txt");

        lb_Instrucciones3.setFont(new java.awt.Font("Rockwell", 0, 14)); // NOI18N
        lb_Instrucciones3.setText("Puedes cargar un Estado Financiero que hayas creado tu mismo pero se recomienda que");

        lb_Instrucciones4.setFont(new java.awt.Font("Rockwell", 0, 14)); // NOI18N
        lb_Instrucciones4.setText("uses el sistema para crear tus Estados Financieros.");

        lb_edos_cargados.setFont(new java.awt.Font("Rockwell", 0, 12)); // NOI18N
        lb_edos_cargados.setText("Estados cargados:");

        Tabla_Estados_cargados.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Nombre", "Tipo"
            }
        ));
        jScrollPane1.setViewportView(Tabla_Estados_cargados);

        btAbrirEstado.setFont(new java.awt.Font("Constantia", 0, 14)); // NOI18N
        btAbrirEstado.setText("Abrir Estado Financiero");
        btAbrirEstado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAbrirEstadoActionPerformed(evt);
            }
        });

        btAnalizarEstado.setFont(new java.awt.Font("Constantia", 0, 14)); // NOI18N
        btAnalizarEstado.setText("Analizar Estado Financiero");
        btAnalizarEstado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAnalizarEstadoActionPerformed(evt);
            }
        });

        btRegresar.setFont(new java.awt.Font("Constantia", 0, 14)); // NOI18N
        btRegresar.setText("Regresar");
        btRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btRegresarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(141, 141, 141)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                            .addComponent(lb_Instrucciones1)
                            .addComponent(lb_titulo)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lb_edos_cargados)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 385, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 74, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(btAbrirEstado)
                                        .addGap(56, 56, 56)
                                        .addComponent(btAnalizarEstado))
                                    .addComponent(btRegresar, javax.swing.GroupLayout.Alignment.TRAILING)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(140, 140, 140)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lb_Instrucciones3)
                            .addComponent(lb_Instrucciones2, javax.swing.GroupLayout.PREFERRED_SIZE, 575, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lb_Instrucciones4, javax.swing.GroupLayout.PREFERRED_SIZE, 575, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(44, 44, 44))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(lb_titulo, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(lb_Instrucciones1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lb_Instrucciones2, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lb_Instrucciones3, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lb_Instrucciones4, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(lb_edos_cargados)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(154, 154, 154)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btAbrirEstado, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btAnalizarEstado, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(154, 154, 154)
                        .addComponent(btRegresar, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 378, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btAbrirEstadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAbrirEstadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btAbrirEstadoActionPerformed

    private void btAnalizarEstadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAnalizarEstadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btAnalizarEstadoActionPerformed

    private void btRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btRegresarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btRegresarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Cargar_Estado_Financiero.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Cargar_Estado_Financiero.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Cargar_Estado_Financiero.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Cargar_Estado_Financiero.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Cargar_Estado_Financiero().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable Tabla_Estados_cargados;
    private javax.swing.JButton btAbrirEstado;
    private javax.swing.JButton btAnalizarEstado;
    private javax.swing.JButton btRegresar;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lb_Instrucciones1;
    private javax.swing.JLabel lb_Instrucciones2;
    private javax.swing.JLabel lb_Instrucciones3;
    private javax.swing.JLabel lb_Instrucciones4;
    private javax.swing.JLabel lb_edos_cargados;
    private javax.swing.JLabel lb_titulo;
    // End of variables declaration//GEN-END:variables
}
