package Vistas;

import Modelo.EstadoFinanciero;
import Modelo.SituacionFinanciera;
import javax.swing.DefaultListModel;

/**
 *
 * @author super
 */
public class Crear_Estado_Situacion_Financiera extends javax.swing.JFrame {

    /**
     * Creates new form Crear_Estado_Situacion_Financiera
     */
        private SituacionFinanciera sf;
        private DefaultListModel lista = new DefaultListModel();
        
    
    public Crear_Estado_Situacion_Financiera() {
        initComponents();
        DefaultListModel l = new DefaultListModel();
        l.addElement("");
        this.ComboBoxNombreCuenta.removeAllItems();
        this.jlCuentasAgregadas.setModel(l);
        this.setVisible(true);
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bts_TipoCuenta = new javax.swing.ButtonGroup();
        bts_Activo = new javax.swing.ButtonGroup();
        bts_Pasivo = new javax.swing.ButtonGroup();
        bts_Capital = new javax.swing.ButtonGroup();
        lbTitulo = new javax.swing.JLabel();
        lbExtension = new javax.swing.JLabel();
        lbNombreSF = new javax.swing.JLabel();
        txtNombreSF = new javax.swing.JTextField();
        lbCuentas = new javax.swing.JLabel();
        RdbActivo = new javax.swing.JRadioButton();
        RdbPasivo = new javax.swing.JRadioButton();
        RdbCapital = new javax.swing.JRadioButton();
        Rdb_A_circulante = new javax.swing.JRadioButton();
        Rdb_A_fijo = new javax.swing.JRadioButton();
        Rdb_A_diferido = new javax.swing.JRadioButton();
        Rdb_P_circulante = new javax.swing.JRadioButton();
        Rdb_P_fijo = new javax.swing.JRadioButton();
        Rdb_P_diferido = new javax.swing.JRadioButton();
        Rdb_C_capSocial = new javax.swing.JRadioButton();
        Rdb_C_UtilidadNeta = new javax.swing.JRadioButton();
        lbNombreCuenta = new javax.swing.JLabel();
        lbSaldoCuenta = new javax.swing.JLabel();
        txtSaldoCuenta = new javax.swing.JTextField();
        btAgregarCuenta = new javax.swing.JButton();
        btFinalizarSF = new javax.swing.JButton();
        btRegresar = new javax.swing.JButton();
        ComboBoxNombreCuenta = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        jlCuentasAgregadas = new javax.swing.JList<>();
        jlbCuentasAgregadas = new javax.swing.JLabel();
        jbCrearEstado = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Crear Estado de Situación Financiera");

        lbTitulo.setFont(new java.awt.Font("Rockwell", 0, 18)); // NOI18N
        lbTitulo.setText("Crear nuevo Estado de Situacion Financiera");

        lbExtension.setFont(new java.awt.Font("Rockwell", 0, 14)); // NOI18N
        lbExtension.setText("Nombre del archivo ");

        lbNombreSF.setFont(new java.awt.Font("Rockwell", 0, 14)); // NOI18N
        lbNombreSF.setText("Ingresa el nombre:");

        lbCuentas.setFont(new java.awt.Font("Rockwell", 0, 16)); // NOI18N
        lbCuentas.setText("Cuentas");

        bts_TipoCuenta.add(RdbActivo);
        RdbActivo.setText("Activo");
        RdbActivo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RdbActivoActionPerformed(evt);
            }
        });

        bts_TipoCuenta.add(RdbPasivo);
        RdbPasivo.setText("Pasivo");

        bts_TipoCuenta.add(RdbCapital);
        RdbCapital.setText("Capital");

        bts_Activo.add(Rdb_A_circulante);
        Rdb_A_circulante.setText("Circulante");
        Rdb_A_circulante.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Rdb_A_circulanteActionPerformed(evt);
            }
        });

        bts_Activo.add(Rdb_A_fijo);
        Rdb_A_fijo.setText("Fijo");
        Rdb_A_fijo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Rdb_A_fijoActionPerformed(evt);
            }
        });

        bts_Activo.add(Rdb_A_diferido);
        Rdb_A_diferido.setText("Diferido");
        Rdb_A_diferido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Rdb_A_diferidoActionPerformed(evt);
            }
        });

        bts_Pasivo.add(Rdb_P_circulante);
        Rdb_P_circulante.setText("Circulante");
        Rdb_P_circulante.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Rdb_P_circulanteActionPerformed(evt);
            }
        });

        bts_Pasivo.add(Rdb_P_fijo);
        Rdb_P_fijo.setText("Fijo");
        Rdb_P_fijo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Rdb_P_fijoActionPerformed(evt);
            }
        });

        bts_Pasivo.add(Rdb_P_diferido);
        Rdb_P_diferido.setText("Diferido");
        Rdb_P_diferido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Rdb_P_diferidoActionPerformed(evt);
            }
        });

        bts_Capital.add(Rdb_C_capSocial);
        Rdb_C_capSocial.setText("Capital Social");
        Rdb_C_capSocial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Rdb_C_capSocialActionPerformed(evt);
            }
        });

        bts_Capital.add(Rdb_C_UtilidadNeta);
        Rdb_C_UtilidadNeta.setText("Utilidad Neta");
        Rdb_C_UtilidadNeta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Rdb_C_UtilidadNetaActionPerformed(evt);
            }
        });

        lbNombreCuenta.setFont(new java.awt.Font("Rockwell", 0, 14)); // NOI18N
        lbNombreCuenta.setText("Nombre de la Cuenta:");

        lbSaldoCuenta.setFont(new java.awt.Font("Rockwell", 0, 14)); // NOI18N
        lbSaldoCuenta.setText("Saldo:");

        btAgregarCuenta.setFont(new java.awt.Font("Constantia", 0, 12)); // NOI18N
        btAgregarCuenta.setText("Agregar");
        btAgregarCuenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAgregarCuentaActionPerformed(evt);
            }
        });

        btFinalizarSF.setFont(new java.awt.Font("Constantia", 0, 12)); // NOI18N
        btFinalizarSF.setText("Guardar Estado");

        btRegresar.setFont(new java.awt.Font("Constantia", 0, 12)); // NOI18N
        btRegresar.setText("Regresar");

        ComboBoxNombreCuenta.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jlCuentasAgregadas.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(jlCuentasAgregadas);

        jlbCuentasAgregadas.setText("Cuentas agregadas.");

        jbCrearEstado.setText("CrearEstado");
        jbCrearEstado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbCrearEstadoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lbExtension, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(651, 651, 651))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(RdbActivo)
                            .addComponent(lbNombreSF))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(0, 0, Short.MAX_VALUE)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(Rdb_C_UtilidadNeta)
                                            .addComponent(Rdb_C_capSocial)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(txtNombreSF, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(81, 81, 81)
                                        .addComponent(jbCrearEstado)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                .addGap(166, 166, 166))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(34, 34, 34)
                                .addComponent(ComboBoxNombreCuenta, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(33, 33, 33)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(lbCuentas)
                                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(RdbPasivo)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(RdbCapital)
                                                .addGap(224, 224, 224))))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(68, 68, 68)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jlbCuentasAgregadas)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 294, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(btFinalizarSF)))
                                        .addContainerGap())))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(100, 100, 100)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Rdb_A_fijo)
                            .addComponent(Rdb_A_circulante)
                            .addComponent(Rdb_A_diferido))
                        .addGap(0, 0, Short.MAX_VALUE))))
            .addGroup(layout.createSequentialGroup()
                .addGap(62, 62, 62)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lbSaldoCuenta)
                            .addComponent(lbNombreCuenta))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtSaldoCuenta, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(68, 68, 68)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Rdb_P_fijo)
                            .addComponent(Rdb_P_diferido)
                            .addComponent(Rdb_P_circulante))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(104, 104, 104)
                        .addComponent(btAgregarCuenta)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(layout.createSequentialGroup()
                .addGap(295, 295, 295)
                .addComponent(lbTitulo)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btRegresar)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(lbTitulo)
                .addGap(42, 42, 42)
                .addComponent(lbExtension)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbNombreSF)
                    .addComponent(txtNombreSF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbCrearEstado))
                .addGap(18, 18, 18)
                .addComponent(lbCuentas)
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(RdbPasivo)
                    .addComponent(RdbActivo)
                    .addComponent(RdbCapital))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Rdb_C_capSocial)
                    .addComponent(Rdb_P_circulante)
                    .addComponent(Rdb_A_circulante))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Rdb_C_UtilidadNeta)
                    .addComponent(Rdb_P_fijo)
                    .addComponent(Rdb_A_fijo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Rdb_P_diferido)
                    .addComponent(Rdb_A_diferido))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbNombreCuenta)
                            .addComponent(ComboBoxNombreCuenta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbSaldoCuenta)
                            .addComponent(txtSaldoCuenta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(47, 47, 47)
                        .addComponent(btAgregarCuenta)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btFinalizarSF)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btRegresar))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 28, Short.MAX_VALUE)
                        .addComponent(jlbCuentasAgregadas)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 262, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void RdbActivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RdbActivoActionPerformed
      
      
            
        
    }//GEN-LAST:event_RdbActivoActionPerformed

    private void Rdb_A_circulanteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Rdb_A_circulanteActionPerformed
           AsignarValoresCB();
    }//GEN-LAST:event_Rdb_A_circulanteActionPerformed

    private void Rdb_A_fijoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Rdb_A_fijoActionPerformed
            AsignarValoresCB();
    }//GEN-LAST:event_Rdb_A_fijoActionPerformed

    private void Rdb_P_circulanteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Rdb_P_circulanteActionPerformed
        AsignarValoresCB();
    }//GEN-LAST:event_Rdb_P_circulanteActionPerformed

    private void Rdb_P_fijoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Rdb_P_fijoActionPerformed
        AsignarValoresCB();
    }//GEN-LAST:event_Rdb_P_fijoActionPerformed

    private void Rdb_P_diferidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Rdb_P_diferidoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Rdb_P_diferidoActionPerformed

    private void Rdb_C_capSocialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Rdb_C_capSocialActionPerformed
        AsignarValoresCB();
    }//GEN-LAST:event_Rdb_C_capSocialActionPerformed

    private void Rdb_C_UtilidadNetaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Rdb_C_UtilidadNetaActionPerformed
       AsignarValoresCB();
    }//GEN-LAST:event_Rdb_C_UtilidadNetaActionPerformed

    private void Rdb_A_diferidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Rdb_A_diferidoActionPerformed
        AsignarValoresCB();
    }//GEN-LAST:event_Rdb_A_diferidoActionPerformed

    private void btAgregarCuentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAgregarCuentaActionPerformed
        String nombrecuenta,saldo;
        int i;
        
        i = this.ComboBoxNombreCuenta.getSelectedIndex();
        saldo = this.txtSaldoCuenta.getText();
        nombrecuenta = this.ComboBoxNombreCuenta.getItemAt(0);
        
        //sf.agregarCuenta(saldo, saldo, saldo, saldo);
        /*
            Para obtener los nombres es mejor usar un combo bo para la clasificacion y usar ifs para el nombre de los 
            radiobuttns
        
        */
        
        
        System.out.println(nombrecuenta + " = "+ saldo);
        
    }//GEN-LAST:event_btAgregarCuentaActionPerformed

    private void jbCrearEstadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbCrearEstadoActionPerformed
        
        if(this.txtNombreSF.getText().isEmpty())
        {   
            System.out.println("Ingresa un nombre a tu sf"); //JOPTION
        }
        else
        {
            SituacionFinanciera situacionfinanciera = new SituacionFinanciera(this.getName()+".txt");
            this.sf =  situacionfinanciera;
        }
        
    }//GEN-LAST:event_jbCrearEstadoActionPerformed

   public void AsignarValoresCB()
   {
         if (this.RdbActivo.isSelected())
        {
            if(this.Rdb_A_circulante.isSelected())
            {
                this.ComboBoxNombreCuenta.removeAllItems();
                this.ComboBoxNombreCuenta.addItem("Caja");
            }
            else
            {
                if(this.Rdb_A_fijo.isSelected())
                {
                    this.ComboBoxNombreCuenta.removeAllItems();
                    this.ComboBoxNombreCuenta.addItem("Terrenos");
                }
                else
                {
                    if (this.Rdb_A_diferido.isSelected())
                    {
                        this.ComboBoxNombreCuenta.removeAllItems();
                        this.ComboBoxNombreCuenta.addItem("Gastos de operacion");
                    }
                    else
                        System.out.println("Selecciona un tipo de cuenta" ); //JOPTION
                }
            }
        }
        else
        {
            if(this.RdbPasivo.isSelected())
            {
                if(this.Rdb_P_circulante.isSelected())
            {
                this.ComboBoxNombreCuenta.removeAllItems();
                this.ComboBoxNombreCuenta.addItem("Clientes");
            }
            else
            {
                if(this.Rdb_P_fijo.isSelected())
                {
                    this.ComboBoxNombreCuenta.removeAllItems();
                    this.ComboBoxNombreCuenta.addItem("Hipotecas por pagar");
                }
                else
                {
                    if (this.Rdb_P_diferido.isSelected())
                    {
                        
                    }
                    else
                        System.out.println("Selecciona un tipo de cuenta" ); //JOPTION
                }
            }
            }
            else
            {
                if(this.RdbCapital.isSelected())
                {
                    if(this.Rdb_C_capSocial.isSelected())
                    {
                        this.ComboBoxNombreCuenta.removeAllItems();
                    this.ComboBoxNombreCuenta.addItem("Capital social");
                    }
                    else
                    {
                        if(this.Rdb_C_UtilidadNeta.isSelected())
                        {
                            this.ComboBoxNombreCuenta.removeAllItems();
                            this.ComboBoxNombreCuenta.addItem("UtilidadNeta");
                        }
                        else
                            System.out.println("Selecciona una cuenta"); //JOPTION
                    }
                }
                else
                {
                    System.out.println("Selecciona una cuenta"); //JOPTION
                }
            }
        }
   }
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> ComboBoxNombreCuenta;
    private javax.swing.JRadioButton RdbActivo;
    private javax.swing.JRadioButton RdbCapital;
    private javax.swing.JRadioButton RdbPasivo;
    private javax.swing.JRadioButton Rdb_A_circulante;
    private javax.swing.JRadioButton Rdb_A_diferido;
    private javax.swing.JRadioButton Rdb_A_fijo;
    private javax.swing.JRadioButton Rdb_C_UtilidadNeta;
    private javax.swing.JRadioButton Rdb_C_capSocial;
    private javax.swing.JRadioButton Rdb_P_circulante;
    private javax.swing.JRadioButton Rdb_P_diferido;
    private javax.swing.JRadioButton Rdb_P_fijo;
    private javax.swing.JButton btAgregarCuenta;
    private javax.swing.JButton btFinalizarSF;
    private javax.swing.JButton btRegresar;
    private javax.swing.ButtonGroup bts_Activo;
    private javax.swing.ButtonGroup bts_Capital;
    private javax.swing.ButtonGroup bts_Pasivo;
    private javax.swing.ButtonGroup bts_TipoCuenta;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton jbCrearEstado;
    private javax.swing.JList<String> jlCuentasAgregadas;
    private javax.swing.JLabel jlbCuentasAgregadas;
    private javax.swing.JLabel lbCuentas;
    private javax.swing.JLabel lbExtension;
    private javax.swing.JLabel lbNombreCuenta;
    private javax.swing.JLabel lbNombreSF;
    private javax.swing.JLabel lbSaldoCuenta;
    private javax.swing.JLabel lbTitulo;
    private javax.swing.JTextField txtNombreSF;
    private javax.swing.JTextField txtSaldoCuenta;
    // End of variables declaration//GEN-END:variables
}
