package Vistas;

import Modelo.Resultados;
import Modelo.SituacionFinanciera;
import java.awt.Image;
import java.io.File;
import javax.swing.DefaultListModel;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JLabel;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author Diego EG
 */
public class Inicio extends javax.swing.JFrame {

    /**
     * Creates new form Inicio
     */
    
    private File estados[];
    
    
    public Inicio() {
        estados = new File[2];
        initComponents();
        this.jpESCOM.setVisible(true);
        this.jpIPN.setVisible(true);
        DefaultListModel lista = new DefaultListModel();
        lista.addElement("Ningun elemento seleccionado");
        lista.addElement("Ningun elemento seleccionado");
               
        this.jListArchivosAbiertos.setModel(lista);
               
        this.jpEdosfinancieros.setVisible(false);
        this.btnCrear_Estado_Financiero.setVisible(false);
        this.jpRealizarAnalisis.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Rdbs_Estados_Financieros = new javax.swing.ButtonGroup();
        lbLogoIPN = new javax.swing.JLabel();
        Fondo = new javax.swing.JPanel();
        Encabezado_1 = new javax.swing.JLabel();
        Encabezado_2 = new javax.swing.JLabel();
        lb_Sis_Financiero = new javax.swing.JLabel();
        lb_integrantes = new javax.swing.JLabel();
        lb_Integrante_1 = new javax.swing.JLabel();
        lb_Integrante_2 = new javax.swing.JLabel();
        lb_Opcion = new javax.swing.JLabel();
        btnCrearEstado = new javax.swing.JButton();
        btnCargarEstado = new javax.swing.JButton();
        jpEdosfinancieros = new javax.swing.JPanel();
        Rdb_Situacion_Financiera = new javax.swing.JRadioButton();
        Rdb_Estado_Resultados = new javax.swing.JRadioButton();
        btnCrear_Estado_Financiero = new javax.swing.JButton();
        RdbFlujoEfectivo = new javax.swing.JRadioButton();
        jpRealizarAnalisis = new javax.swing.JPanel();
        jlEdosCargados = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jListArchivosAbiertos = new javax.swing.JList<>();
        jbAnalisisFinanciero = new javax.swing.JButton();
        jbCerrarEstado = new javax.swing.JButton();
        jpIPN = new javax.swing.JPanel();
        logoIPN = new javax.swing.JLabel();
        jpESCOM = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Sistema Financiero");
        setBackground(new java.awt.Color(153, 204, 255));
        setName("FormInicio"); // NOI18N
        setResizable(false);
        setSize(new java.awt.Dimension(500, 500));

        Fondo.setBackground(new java.awt.Color(153, 204, 255));

        Encabezado_1.setFont(new java.awt.Font("Rockwell", 1, 16)); // NOI18N
        Encabezado_1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Encabezado_1.setText("INSTITUTO POLITÉCNICO NACIONAL");
        Encabezado_1.setToolTipText("");

        Encabezado_2.setFont(new java.awt.Font("Rockwell", 1, 16)); // NOI18N
        Encabezado_2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Encabezado_2.setText("ESCUELA SUPERIOR DE CÓMPUTO");
        Encabezado_2.setToolTipText("");

        lb_Sis_Financiero.setFont(new java.awt.Font("Rockwell", 1, 18)); // NOI18N
        lb_Sis_Financiero.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lb_Sis_Financiero.setText("Sistema Financiero");

        lb_integrantes.setFont(new java.awt.Font("Rockwell", 1, 16)); // NOI18N
        lb_integrantes.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lb_integrantes.setText("Integrantes:");

        lb_Integrante_1.setFont(new java.awt.Font("Rockwell", 1, 14)); // NOI18N
        lb_Integrante_1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lb_Integrante_1.setText("Castillo Jiménez Jorge");

        lb_Integrante_2.setFont(new java.awt.Font("Rockwell", 1, 14)); // NOI18N
        lb_Integrante_2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lb_Integrante_2.setText("Estrada Granados Diego");

        lb_Opcion.setFont(new java.awt.Font("Rockwell", 0, 18)); // NOI18N
        lb_Opcion.setText("Seleccione una opción:");

        btnCrearEstado.setBackground(new java.awt.Color(255, 255, 255));
        btnCrearEstado.setFont(new java.awt.Font("MS Reference Sans Serif", 1, 14)); // NOI18N
        btnCrearEstado.setText("Crear Estado Financiero");
        btnCrearEstado.setName("bt Crear Estado Financiero"); // NOI18N
        btnCrearEstado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCrearEstadoActionPerformed(evt);
            }
        });

        btnCargarEstado.setBackground(new java.awt.Color(255, 255, 255));
        btnCargarEstado.setFont(new java.awt.Font("MS Reference Sans Serif", 1, 14)); // NOI18N
        btnCargarEstado.setText("Cargar Estado Financiero");
        btnCargarEstado.setName("bt Cargar Estado"); // NOI18N
        btnCargarEstado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCargarEstadoActionPerformed(evt);
            }
        });

        jpEdosfinancieros.setBackground(new java.awt.Color(153, 204, 255));

        Rdb_Situacion_Financiera.setBackground(new java.awt.Color(153, 204, 255));
        Rdbs_Estados_Financieros.add(Rdb_Situacion_Financiera);
        Rdb_Situacion_Financiera.setFont(new java.awt.Font("Times New Roman", 1, 11)); // NOI18N
        Rdb_Situacion_Financiera.setText("Situación Financiera");
        Rdb_Situacion_Financiera.setToolTipText("");
        Rdb_Situacion_Financiera.setName("rdb SF"); // NOI18N

        Rdb_Estado_Resultados.setBackground(new java.awt.Color(153, 204, 255));
        Rdbs_Estados_Financieros.add(Rdb_Estado_Resultados);
        Rdb_Estado_Resultados.setFont(new java.awt.Font("Times New Roman", 1, 11)); // NOI18N
        Rdb_Estado_Resultados.setText("Estado de Resultados");
        Rdb_Estado_Resultados.setName("rdb ER"); // NOI18N

        btnCrear_Estado_Financiero.setBackground(new java.awt.Color(255, 255, 255));
        btnCrear_Estado_Financiero.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        btnCrear_Estado_Financiero.setText("Crear");
        btnCrear_Estado_Financiero.setName("bt Crear"); // NOI18N
        btnCrear_Estado_Financiero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCrear_Estado_FinancieroActionPerformed(evt);
            }
        });

        RdbFlujoEfectivo.setBackground(new java.awt.Color(153, 204, 255));
        Rdbs_Estados_Financieros.add(RdbFlujoEfectivo);
        RdbFlujoEfectivo.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        RdbFlujoEfectivo.setText("Flujo de Efectivo");
        RdbFlujoEfectivo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RdbFlujoEfectivoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jpEdosfinancierosLayout = new javax.swing.GroupLayout(jpEdosfinancieros);
        jpEdosfinancieros.setLayout(jpEdosfinancierosLayout);
        jpEdosfinancierosLayout.setHorizontalGroup(
            jpEdosfinancierosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpEdosfinancierosLayout.createSequentialGroup()
                .addGap(69, 69, 69)
                .addComponent(btnCrear_Estado_Financiero)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jpEdosfinancierosLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(jpEdosfinancierosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpEdosfinancierosLayout.createSequentialGroup()
                        .addComponent(RdbFlujoEfectivo)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(Rdb_Estado_Resultados, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Rdb_Situacion_Financiera, javax.swing.GroupLayout.DEFAULT_SIZE, 176, Short.MAX_VALUE))
                .addContainerGap())
        );
        jpEdosfinancierosLayout.setVerticalGroup(
            jpEdosfinancierosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpEdosfinancierosLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(Rdb_Situacion_Financiera, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Rdb_Estado_Resultados)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(RdbFlujoEfectivo)
                .addGap(23, 23, 23)
                .addComponent(btnCrear_Estado_Financiero, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(48, 48, 48))
        );

        jpRealizarAnalisis.setBackground(new java.awt.Color(153, 204, 255));

        jlEdosCargados.setBackground(new java.awt.Color(0, 153, 255));
        jlEdosCargados.setFont(new java.awt.Font("Rockwell", 0, 14)); // NOI18N
        jlEdosCargados.setText("Estados Financieros cargados:");

        jListArchivosAbiertos.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(jListArchivosAbiertos);

        jbAnalisisFinanciero.setBackground(new java.awt.Color(255, 255, 255));
        jbAnalisisFinanciero.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jbAnalisisFinanciero.setText("Análisis financero");
        jbAnalisisFinanciero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbAnalisisFinancieroActionPerformed(evt);
            }
        });

        jbCerrarEstado.setBackground(new java.awt.Color(255, 255, 255));
        jbCerrarEstado.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jbCerrarEstado.setText("Cerrar estado");
        jbCerrarEstado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbCerrarEstadoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jpRealizarAnalisisLayout = new javax.swing.GroupLayout(jpRealizarAnalisis);
        jpRealizarAnalisis.setLayout(jpRealizarAnalisisLayout);
        jpRealizarAnalisisLayout.setHorizontalGroup(
            jpRealizarAnalisisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpRealizarAnalisisLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(jpRealizarAnalisisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(jpRealizarAnalisisLayout.createSequentialGroup()
                        .addComponent(jbCerrarEstado)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jbAnalisisFinanciero))
                    .addGroup(jpRealizarAnalisisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jlEdosCargados)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 294, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jpRealizarAnalisisLayout.setVerticalGroup(
            jpRealizarAnalisisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpRealizarAnalisisLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jlEdosCargados)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 25, Short.MAX_VALUE)
                .addGroup(jpRealizarAnalisisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbAnalisisFinanciero)
                    .addComponent(jbCerrarEstado))
                .addContainerGap())
        );

        jpIPN.setBackground(new java.awt.Color(153, 204, 255));

        logoIPN.setIcon(new javax.swing.ImageIcon("C:\\Users\\super\\Documents\\NetBeansProjects\\Sistema Financiero\\LOGOIPN.png")); // NOI18N

        javax.swing.GroupLayout jpIPNLayout = new javax.swing.GroupLayout(jpIPN);
        jpIPN.setLayout(jpIPNLayout);
        jpIPNLayout.setHorizontalGroup(
            jpIPNLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(logoIPN, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jpIPNLayout.setVerticalGroup(
            jpIPNLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(logoIPN, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jpESCOM.setBackground(new java.awt.Color(153, 204, 255));

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\super\\Documents\\NetBeansProjects\\Sistema Financiero\\LOGOESCOM.png")); // NOI18N

        javax.swing.GroupLayout jpESCOMLayout = new javax.swing.GroupLayout(jpESCOM);
        jpESCOM.setLayout(jpESCOMLayout);
        jpESCOMLayout.setHorizontalGroup(
            jpESCOMLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE)
        );
        jpESCOMLayout.setVerticalGroup(
            jpESCOMLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout FondoLayout = new javax.swing.GroupLayout(Fondo);
        Fondo.setLayout(FondoLayout);
        FondoLayout.setHorizontalGroup(
            FondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(FondoLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(FondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(FondoLayout.createSequentialGroup()
                        .addGroup(FondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lb_Opcion)
                            .addGroup(FondoLayout.createSequentialGroup()
                                .addComponent(btnCrearEstado, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(56, 56, 56)
                                .addComponent(btnCargarEstado)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, FondoLayout.createSequentialGroup()
                        .addGroup(FondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(FondoLayout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addGroup(FondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, FondoLayout.createSequentialGroup()
                                        .addComponent(Encabezado_1, javax.swing.GroupLayout.PREFERRED_SIZE, 324, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(31, 31, 31))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, FondoLayout.createSequentialGroup()
                                        .addComponent(Encabezado_2)
                                        .addGap(46, 46, 46))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, FondoLayout.createSequentialGroup()
                                        .addGroup(FondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(lb_Integrante_1)
                                            .addComponent(lb_Sis_Financiero)
                                            .addComponent(lb_Integrante_2))
                                        .addGap(107, 107, 107)))
                                .addComponent(jpESCOM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(FondoLayout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(jpEdosfinancieros, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 45, Short.MAX_VALUE)
                                .addComponent(jpRealizarAnalisis, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(24, 24, 24))))
            .addGroup(FondoLayout.createSequentialGroup()
                .addGroup(FondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(FondoLayout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(jpIPN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(FondoLayout.createSequentialGroup()
                        .addGap(264, 264, 264)
                        .addComponent(lb_integrantes)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        FondoLayout.setVerticalGroup(
            FondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(FondoLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(FondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(FondoLayout.createSequentialGroup()
                        .addComponent(Encabezado_1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Encabezado_2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lb_Sis_Financiero))
                    .addComponent(jpIPN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jpESCOM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addComponent(lb_integrantes)
                .addGap(18, 18, 18)
                .addComponent(lb_Integrante_1)
                .addGap(18, 18, 18)
                .addComponent(lb_Integrante_2)
                .addGap(19, 19, 19)
                .addComponent(lb_Opcion)
                .addGap(18, 18, 18)
                .addGroup(FondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCrearEstado)
                    .addComponent(btnCargarEstado))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(FondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jpEdosfinancieros, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jpRealizarAnalisis, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(Fondo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbLogoIPN))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(106, 106, 106)
                .addComponent(lbLogoIPN, javax.swing.GroupLayout.DEFAULT_SIZE, 285, Short.MAX_VALUE)
                .addGap(161, 161, 161))
            .addComponent(Fondo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCrearEstadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCrearEstadoActionPerformed
        this.jpEdosfinancieros.setVisible(true);
        this.btnCrear_Estado_Financiero.setVisible(true);
        this.jpRealizarAnalisis.setVisible(false);
    }//GEN-LAST:event_btnCrearEstadoActionPerformed

    private void btnCargarEstadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCargarEstadoActionPerformed
        this.jpRealizarAnalisis.setVisible(true);
        this.jpEdosfinancieros.setVisible(false);
        this.jpRealizarAnalisis.setVisible(true);
        this.btnCrear_Estado_Financiero.setVisible(false);
        JFileChooser abrredo = new JFileChooser();
        FileNameExtensionFilter extension = new FileNameExtensionFilter("Estados finacieros(*.txt)", "txt");
        abrredo.setDialogTitle("Selecciona un estado financiero");
        abrredo.setFileFilter(extension);
        abrredo.showDialog(this, "Seleccionar");
        
        //La posicion 0 del array es situacion financiera y la 1 resultados
        
        try {
            File archivo = abrredo.getSelectedFile();
            //System.out.println("rchivo leido "+archivo);
            agregarEdoFinancieroLista((DefaultListModel)this.jListArchivosAbiertos.getModel(), archivo);
            
        }catch(Exception e){
            System.out.println("Excepcion ->"+e.getMessage());
        }
              
        
        //System.out.println("Archivos generados Resultados->>>>"+ estados[1] );
        //System.out.println("Archivos generados Situacion->>>>"+ estados[0] );
    }//GEN-LAST:event_btnCargarEstadoActionPerformed

    private void jbCerrarEstadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbCerrarEstadoActionPerformed
        int i = this.jListArchivosAbiertos.getSelectedIndex();
        String nombre = this.jListArchivosAbiertos.getSelectedValue();
        //System.out.println("->>>>  "+nombre);
        if(nombre.contains("Situacion")){
             estados[0] = null;}
        else{
             estados[1] = null;}
        
        cerrarEstadoFinanciero((DefaultListModel)this.jListArchivosAbiertos.getModel(), i);
    }//GEN-LAST:event_jbCerrarEstadoActionPerformed

    private void jbAnalisisFinancieroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbAnalisisFinancieroActionPerformed
       
        String nombre1,nombre2;
        //String sf,er;
        
        if(estados[0]==null || estados[1]==null)
            //JOPTION
             Ventana.ShowWarningMessage("Algun archivo no esta abierto");
        else{
            nombre1 = estados[0].getName();
            nombre2 = estados[1].getName();
        //System.out.println("->>>>>"+estados[0].getName());
        //System.out.println("->>>>"+estados[1].getName());
        
            if  ((nombre1.contains("Resultados") ||  nombre1.contains("Situacion")) 
                    && 
                (nombre1.contains("Resultados") ||  nombre1.contains("Situacion"))
                 
                    &&
                !( (nombre1.contains("Resultados") && nombre2.contains("Resultados")) || (nombre1.contains("Situacion")&&nombre2.contains("Situacion"))  )
                )
                
            {
                Ventana.ShowInformationMessage("¡Estados correctos!");
                //System.out.println("***********Estados correctos");
                
                //SituacionFinanciera sf = new SituacionFinanciera(estados[0]);
                //Resultados er = new Resultados(estados[1]);
                
                AnalisisEF formularioAnalisis = new AnalisisEF(estados[0], estados[1]);
                formularioAnalisis.setVisible(true);
                this.setVisible(false);
                /*
                System.out.println("------------------------------------------");
                System.out.println("ER");
                er.leerEstadoFinanciero();
                er.mostrarCuentas();
                
                */
                
            }
            else   
               Ventana.ShowErrorMessage("Alguno de los archivos que selecconaste no tiene el formato para ser leido");  //JOPTION
        
            
            System.out.println("Aqui "+estados[0]);
            System.out.println(estados[1]);
            
             
            
          
        //Aqui se llamara al nuevo formulario para visualizar el analisis con los nombres pasados para 
        }
        
    }//GEN-LAST:event_jbAnalisisFinancieroActionPerformed

    private void btnCrear_Estado_FinancieroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCrear_Estado_FinancieroActionPerformed
        
        
            if(this.Rdb_Estado_Resultados.isSelected())
            {
               Crear_Estado_Resultados formularioEstadoResultados = new Crear_Estado_Resultados();
               this.setVisible(false);
               
            }
            else
            {
                if(this.Rdb_Situacion_Financiera.isSelected())
                {
                    Crear_Estado_Situacion_Financiera formularioSF = new Crear_Estado_Situacion_Financiera();
                    this.setVisible(false);
                }
                else
                    Ventana.ShowInformationMessage("Selecciona una opción"); //JOPTION
            }
        
        
            
    }//GEN-LAST:event_btnCrear_Estado_FinancieroActionPerformed

    private void RdbFlujoEfectivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RdbFlujoEfectivoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RdbFlujoEfectivoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
               
               Inicio formularioInicio = new Inicio();
               formularioInicio.setVisible(true);
               
               
         
    }
    
    public  void agregarEdoFinancieroLista(DefaultListModel lista, File estado)
    {
        String defecto = "Ningun elemento seleccionado";
        String nombre  = estado.getName();
        if (lista.firstElement().equals(defecto)) {
            lista.set(0,nombre);
             if(nombre.contains("Situacion"))
             estados[0] = estado;
             else
             estados[1] = estado;
        }
        else 
        {
            if(lista.lastElement().equals(defecto)){
             lista.set(1,nombre);
             if(nombre.contains("Situacion"))
             estados[0] = estado;
             else
             estados[1] = estado;
            }
            else
            {
                //Aqui debe ir in JOPtion para que diga que ya no se pueden agregar mas estados
                Ventana.ShowErrorMessage("Solo es posible realizar el analisis de 2 estados financieros");
            }
        }
        //System.out.println(estados[0].isFile());
         //System.out.println(estados[1].isFile());
    }
    
    public void cerrarEstadoFinanciero(DefaultListModel lista, int elementoseleccionado )
    {
       
        if(elementoseleccionado<0)
        {
            Ventana.ShowInformationMessage("Selecciona un archivo a ser cerrado");
            
        }
        else
        {
            /*
                ------ATENCION------
                Una manera de evitar que cuando se cierren los archivos se tengan los dos abuertos
                Puede NO ser la opcion usar el metodo .delete() porque borra el archivo creado, tampoco podria ser
                una opcion mandarlo a null para evitar los apuntadores a nulos al hacer la transicion a otro form
            
                Podemos usar los textos de la lista, verificando que los dos sean diferentes que el estadocerrado
                (Ningun elemento seleccionado), ademas podriamos verificar que tenga algun nombre en especial el archivo
                que abrio el usuario
            
                --------RESUELTO-----------
                Es necesrio verificar si los archivos son == a null para que entre en el if declarado en el metodo
                
            */
            
                    
            //lista.removeElementAt(elementoselecionado);
            estados[elementoseleccionado]=null;
            mandaraEstadoCerrado(lista, elementoseleccionado);
        }
    }
    
    public  void mandaraEstadoCerrado(DefaultListModel lista, int i)
    {
        String nombre = "Ningun elemento seleccionado";
        lista.set(i,nombre);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Encabezado_1;
    private javax.swing.JLabel Encabezado_2;
    private javax.swing.JPanel Fondo;
    private javax.swing.JRadioButton RdbFlujoEfectivo;
    private javax.swing.JRadioButton Rdb_Estado_Resultados;
    private javax.swing.JRadioButton Rdb_Situacion_Financiera;
    private javax.swing.ButtonGroup Rdbs_Estados_Financieros;
    private javax.swing.JButton btnCargarEstado;
    private javax.swing.JButton btnCrearEstado;
    private javax.swing.JButton btnCrear_Estado_Financiero;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JList<String> jListArchivosAbiertos;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton jbAnalisisFinanciero;
    private javax.swing.JButton jbCerrarEstado;
    private javax.swing.JLabel jlEdosCargados;
    private javax.swing.JPanel jpESCOM;
    private javax.swing.JPanel jpEdosfinancieros;
    private javax.swing.JPanel jpIPN;
    private javax.swing.JPanel jpRealizarAnalisis;
    private javax.swing.JLabel lbLogoIPN;
    private javax.swing.JLabel lb_Integrante_1;
    private javax.swing.JLabel lb_Integrante_2;
    private javax.swing.JLabel lb_Opcion;
    private javax.swing.JLabel lb_Sis_Financiero;
    private javax.swing.JLabel lb_integrantes;
    private javax.swing.JLabel logoIPN;
    // End of variables declaration//GEN-END:variables
}
